[package]
name = "starkfish"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.0.2"
#alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[tool.snforge]
# exit_first = true
