declare:
	starkli declare target/dev/starkfish_Starkfish.sierra.json \
	--compiler-version 2.1.0 \
	--rpc http://0.0.0.0:5050 \
	--account ~/.starkli-wallets/deployer/account0_account.json \
	--keystore  ~/.starkli-wallets/deployer/account0_keystore.json

deploy: 
	starkli deploy 0x013e9e50c4ed924338ad958d6a2c19148cb82913d4b9ee2634731c8afe5a75e2 \
	--rpc http://0.0.0.0:5050 \
	--account ~/.starkli-wallets/deployer/account0_account.json \
	--keystore ~/.starkli-wallets/deployer/account0_keystore.json

